// <auto-generated />
using System;
using HorseRacing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HorseRacing.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HorseRacing.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("AppUser", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Bet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Odds")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<long?>("RaceEntryId")
                        .HasColumnType("bigint");

                    b.Property<long>("RaceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HorseId");

                    b.HasIndex("RaceEntryId");

                    b.HasIndex("RaceId");

                    b.HasIndex("UserId");

                    b.ToTable("Bet", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Financials.Prize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("JockeyPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("OwnerPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("RankPosition")
                        .HasColumnType("int");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "RankPosition")
                        .IsUnique();

                    b.ToTable("Prize", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Horse", b =>
                {
                    b.Property<int>("HorseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HorseId"));

                    b.Property<DateTime>("Age")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("AverageTime")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HealthStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("RecentAverageTime")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("WinRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("HorseId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Horse", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.HorseDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HorseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HorseId");

                    b.ToTable("HorseDocument", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.HorseStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageSpeed")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("HorseId")
                        .HasColumnType("int");

                    b.Property<int>("TotalRaces")
                        .HasColumnType("int");

                    b.Property<int>("TotalSecondPlaces")
                        .HasColumnType("int");

                    b.Property<int>("TotalThirdPlaces")
                        .HasColumnType("int");

                    b.Property<int>("TotalWins")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HorseId")
                        .IsUnique();

                    b.ToTable("HorseStatistic", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.JockeyContract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InvitationExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JockeyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.HasKey("ContractId");

                    b.HasIndex("HorseId");

                    b.HasIndex("JockeyId");

                    b.HasIndex("TournamentId", "HorseId", "JockeyId")
                        .IsUnique();

                    b.ToTable("JockeyContract", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.JockeyProfile", b =>
                {
                    b.Property<int>("JockeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JockeyId"));

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<int>("RankingPoint")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("JockeyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("JockeyProfile", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.MedicalCheckRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CheckType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DopingResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FailReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("int");

                    b.Property<int?>("HorseId")
                        .HasColumnType("int");

                    b.Property<string>("MedicalResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Temperature")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("HorseId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("UserId");

                    b.ToTable("MedicalCheckRecord", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Payout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BetId");

                    b.ToTable("Payout", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Prediction", b =>
                {
                    b.Property<int>("PredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PredictionId"));

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.Property<DateTime>("PredictedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("RaceEntryId")
                        .HasColumnType("bigint");

                    b.Property<long>("RaceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PredictionId");

                    b.HasIndex("RaceEntryId");

                    b.HasIndex("RaceId");

                    b.HasIndex("UserId", "RaceId")
                        .IsUnique();

                    b.ToTable("Prediction", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceEntry", b =>
                {
                    b.Property<long>("RaceEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RaceEntryId"));

                    b.Property<decimal?>("CurrentOdds")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("FinishPosition")
                        .HasColumnType("int");

                    b.Property<decimal?>("FinishTime")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("JockeyId")
                        .HasColumnType("int");

                    b.Property<int>("LaneNo")
                        .HasColumnType("int");

                    b.Property<long>("RaceId")
                        .HasColumnType("bigint");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WinningProbability")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("WithdrawReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("WithdrawTime")
                        .HasColumnType("datetime2");

                    b.HasKey("RaceEntryId");

                    b.HasIndex("JockeyId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("RaceId", "LaneNo")
                        .IsUnique();

                    b.HasIndex("RaceId", "RegistrationId")
                        .IsUnique();

                    b.ToTable("RaceEntry", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("RaceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ResultRecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Winner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceResult", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceViolation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Penalty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RaceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceViolation", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RefereeProfile", b =>
                {
                    b.Property<int>("RefereeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefereeId"));

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RefereeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefereeProfile", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RefereeReport", b =>
                {
                    b.Property<long>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReportId"));

                    b.Property<long>("AssignmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReportedHorseId")
                        .HasColumnType("int");

                    b.Property<int?>("ReportedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ViolationNote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("ReportedHorseId");

                    b.HasIndex("ReportedUserId");

                    b.ToTable("RefereeReport", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<int>("HorseId")
                        .HasColumnType("int")
                        .HasColumnName("HorseId");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.HasKey("RegistrationId");

                    b.HasIndex("HorseId");

                    b.HasIndex("TournamentId", "HorseId")
                        .IsUnique();

                    b.ToTable("Registration", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "HorseOwner"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Jockey"
                        },
                        new
                        {
                            RoleId = 4,
                            Name = "Referee"
                        },
                        new
                        {
                            RoleId = 5,
                            Name = "Spectator"
                        },
                        new
                        {
                            RoleId = 6,
                            Name = "Veterinarian"
                        });
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.TournamentPrizePayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("UserId");

                    b.ToTable("TournamentPrizePayout", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.Race", b =>
                {
                    b.Property<long>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RaceId"));

                    b.Property<int>("DistanceMeter")
                        .HasColumnType("int");

                    b.Property<int>("MaxLanes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RaceDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("RoundId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RaceId");

                    b.HasIndex("RoundId");

                    b.ToTable("Race", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.RaceRefereeAssignment", b =>
                {
                    b.Property<long>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssignmentId"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("RaceId")
                        .HasColumnType("bigint");

                    b.Property<int>("RefereeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("RefereeId");

                    b.HasIndex("RaceId", "RefereeId")
                        .IsUnique();

                    b.ToTable("RaceRefereeAssignment", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.Round", b =>
                {
                    b.Property<long>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoundId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.HasKey("RoundId");

                    b.HasIndex("TournamentId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("Round", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.Tournament", b =>
                {
                    b.Property<long>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TournamentId"));

                    b.Property<int>("CancelCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegistrationEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RegistrationStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TournamentId");

                    b.ToTable("Tournament", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletId"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallet", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GatewayTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PayoutId")
                        .HasColumnType("int");

                    b.Property<int?>("PrizePayoutId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("BetId");

                    b.HasIndex("PayoutId");

                    b.HasIndex("PrizePayoutId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransaction", (string)null);
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Bet", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Horse", "Horse")
                        .WithMany()
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.RaceEntry", "RaceEntry")
                        .WithMany()
                        .HasForeignKey("RaceEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("Race");

                    b.Navigation("RaceEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Financials.Prize", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Horse", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "Owner")
                        .WithMany("Horses")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.HorseDocument", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Horse", "Horse")
                        .WithMany("Documents")
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horse");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.HorseStatistic", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Horse", "Horse")
                        .WithOne("Statistic")
                        .HasForeignKey("HorseRacing.Domain.Entities.HorseStatistic", "HorseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horse");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.JockeyContract", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Horse", "Horse")
                        .WithMany()
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "Jockey")
                        .WithMany()
                        .HasForeignKey("JockeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("Jockey");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.JockeyProfile", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "User")
                        .WithOne()
                        .HasForeignKey("HorseRacing.Domain.Entities.JockeyProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.MedicalCheckRecord", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Horse", "Horse")
                        .WithMany()
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HorseRacing.Domain.Entities.Registration", "Registration")
                        .WithMany("MedicalCheckRecords")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "Veterinarian")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("Registration");

                    b.Navigation("Veterinarian");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Notification", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Payout", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Bet", "Bet")
                        .WithMany()
                        .HasForeignKey("BetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bet");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Prediction", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.RaceEntry", "RaceEntry")
                        .WithMany()
                        .HasForeignKey("RaceEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("RaceEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceEntry", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.JockeyProfile", "JockeyProfile")
                        .WithMany()
                        .HasForeignKey("JockeyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.Registration", "Registration")
                        .WithMany()
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JockeyProfile");

                    b.Navigation("Race");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceResult", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceViolation", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RefereeProfile", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "User")
                        .WithOne()
                        .HasForeignKey("HorseRacing.Domain.Entities.RefereeProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RefereeReport", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.RaceRefereeAssignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.Horse", "ReportedHorse")
                        .WithMany()
                        .HasForeignKey("ReportedHorseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "ReportedUser")
                        .WithMany()
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assignment");

                    b.Navigation("ReportedHorse");

                    b.Navigation("ReportedUser");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Registration", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Horse", "Horse")
                        .WithMany("Registrations")
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.TournamentPrizePayout", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.Race", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Round", "Round")
                        .WithMany("Races")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.RaceRefereeAssignment", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Race", "Race")
                        .WithMany("RaceRefereeAssignments")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.RefereeProfile", "RefereeProfile")
                        .WithMany()
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("RefereeProfile");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.Round", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Tournament", "Tournament")
                        .WithMany("Rounds")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "User")
                        .WithOne()
                        .HasForeignKey("HorseRacing.Domain.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Bet", "Bet")
                        .WithMany()
                        .HasForeignKey("BetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HorseRacing.Domain.Entities.Payout", "Payout")
                        .WithMany()
                        .HasForeignKey("PayoutId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HorseRacing.Domain.Entities.TournamentPrizePayout", "TournamentPrizePayout")
                        .WithMany()
                        .HasForeignKey("PrizePayoutId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HorseRacing.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bet");

                    b.Navigation("Payout");

                    b.Navigation("TournamentPrizePayout");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Horses");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Horse", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Registrations");

                    b.Navigation("Statistic");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Registration", b =>
                {
                    b.Navigation("MedicalCheckRecords");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.Race", b =>
                {
                    b.Navigation("RaceRefereeAssignments");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.Round", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.Tournament", b =>
                {
                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
